# Generated by Django 5.1.7 on 2025-03-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
