# Generated by Django 5.1.7 on 2025-03-21 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_vitals', models.JSONField()),
                ('medical_history', models.JSONField()),
                ('current_condition', models.TextField()),
                ('prescribed_medicine', models.JSONField()),
                ('lab_tests', models.JSONField()),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('doctor_details', models.JSONField()),
                ('hospital_details', models.JSONField()),
                ('insurance_details', models.JSONField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
