# Generated by Django 5.1.7 on 2025-03-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='prescribed_medicine',
            new_name='prescribed_medicines',
        ),
    ]
