# Generated by Django 5.1.7 on 2025-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_app', '0002_rename_prescribed_medicine_patientrecord_prescribed_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='Medical_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
